#!/bin/bash
#
# Builds Revive.app — a one-click Mac launcher that starts the dev server
# and opens the dashboard in your default browser.
#
# Result lives at ~/Applications/Revive.app — drag it to your Dock for
# one-click launch, like any other Mac app.
#
# Re-run this script any time the launcher script changes (it overwrites
# the existing .app bundle).

set -euo pipefail

# Locate this repo (works whether you run from repo root or scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

APP_DIR="$HOME/Applications/Revive.app"

echo "Building Revive.app …"
echo "  repo:   $REPO_DIR"
echo "  output: $APP_DIR"

# Reset the bundle
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"

# Launcher script — bakes in this repo's path
cat > "$APP_DIR/Contents/MacOS/revive" <<EOF
#!/bin/bash
#
# Revive launcher. Generated by scripts/build-mac-app.sh on \$(date).
# Edit the script in the repo and re-run the build script to regenerate.

set -e

REVIVE_DIR="$REPO_DIR"
PORT=3000
LOG="/tmp/revive-launcher.log"
PIDFILE="/tmp/revive-launcher.pid"

# GUI apps don't inherit your shell PATH — make sure node + npm are findable
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\$PATH"
if [ -d "\$HOME/.nvm" ]; then
    export NVM_DIR="\$HOME/.nvm"
    # shellcheck disable=SC1091
    [ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
fi

show_error() {
    osascript -e "display dialog \"Revive: \$1\\nCheck \$LOG for details.\" with title \"Revive\" buttons {\"OK\"} default button 1 with icon stop"
}

if [ ! -d "\$REVIVE_DIR" ]; then
    show_error "Project directory not found at \$REVIVE_DIR"
    exit 1
fi

# Already running? Just open the browser.
if curl -fsS "http://localhost:\$PORT/api/config" >/dev/null 2>&1; then
    open "http://localhost:\$PORT"
    exit 0
fi

cd "\$REVIVE_DIR"

# Spawn the dev server fully detached
{
    echo "=== \$(date) starting dev server ==="
    npm run dev
} >"\$LOG" 2>&1 &
echo \$! >"\$PIDFILE"
disown 2>/dev/null || true

# Wait up to 60s for the server
for _ in \$(seq 1 60); do
    if curl -fsS "http://localhost:\$PORT/api/config" >/dev/null 2>&1; then
        open "http://localhost:\$PORT"
        exit 0
    fi
    sleep 1
done

show_error "Dev server didn't come up in 60s"
exit 1
EOF

chmod +x "$APP_DIR/Contents/MacOS/revive"

# Info.plist
cat > "$APP_DIR/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>revive</string>
    <key>CFBundleIdentifier</key>
    <string>com.revive.launcher</string>
    <key>CFBundleName</key>
    <string>Revive</string>
    <key>CFBundleDisplayName</key>
    <string>Revive</string>
    <key>CFBundleVersion</key>
    <string>1.0.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>LSUIElement</key>
    <false/>
    <key>LSBackgroundOnly</key>
    <false/>
</dict>
</plist>
EOF

echo
echo "✓ Revive.app built at $APP_DIR"
echo "  Drag it to your Dock for one-click launch."
echo "  First click: starts dev server (~5s) + opens browser."
echo "  Subsequent clicks: reuses running server, just opens browser."
